const ActionTypes = {
  FETCHING_VEHICLE_DETAILS: 'FETCHING_VEHICLE_DETAILS',
  FETCHING_VEHICLES_SUCCESS: 'FETCHING_VEHICLES_SUCCESS',
  EDIT_VEHICLE_PROPERTY: 'EDIT_VEHICLE_PROPERTY',
  SUBMITTING_UPDATED_VEHICLE: 'SUBMITTING_UPDATED_VEHICLE',
  SUBMIT_UPDATED_VEHICLE_SUCCESS: 'SUBMIT_UPDATED_VEHICLE_SUCCESS',
  SUBMIT_UPDATED_VEHICLE_FAILED: 'SUBMIT_UPDATED_VEHICLE_FAILED',
  SUBMITTING_CREATED_VEHICLE: 'SUBMITTING_CREATED_VEHICLE',
  SUBMIT_CREATED_VEHICLE_SUCCESS: 'SUBMIT_CREATED_VEHICLE_SUCCESS',
  SUBMIT_CREATED_VEHICLE_FAILED: 'SUBMIT_CREATED_VEHICLE_FAILED',
  DELETING_VEHICLE: 'DELETING_VEHICLE',
  DELETE_VEHICLE_SUCCESS: 'DELETE_VEHICLE_SUCCESS',
  DELETE_VEHICLE_FAILED: 'DELETE_VEHICLE_FAILED',
  CLOSE_ALERT_BAR: 'CLOSE_ALERT_BAR'
};

export default ActionTypes;